FROM mcr.microsoft.com/devcontainers/python:24.3.0-0

RUN sudo apt-get update && sudo apt-get install -y \
    libx11-xcb1 \
    libxrender1 \
    libxcb-render0 \
    libxcb-shm0 \
    libxcb1 \
    libxext6 \
    libsm6 \
    libglib2.0-0
